# Generated by Django 3.1.1 on 2021-02-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='mobile',
            new_name='department',
        ),
    ]
