# Generated by Django 3.1.1 on 2021-02-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_auto_20210221_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='department',
            new_name='insitution',
        ),
    ]
